VERSION="2.0.0"
FEDERATION_SERVER="https://stellarid.io/federation/"



ACCOUNTS=[
"GAHOVX34KDN2VEXVBTVKKBN57MDZSBCQFFSN7K6AXWVJDL6AZNM3MTZG",
"GDGGIT3AXOQ25CCRECFJZQRHAXBSOBRTQ4C3XFCDPO3Q6MLM4M23S7TE"
]

[DOCUMENTATION]
ORG_NAME="Sword & Shield"
ORG_LOGO="https://i.ibb.co/k5vP9xV/photo-2021-10-10-09-08-57-removebg-preview.png"
ORG_DESCRIPTION="The coin that included a new type of protection (Sword and Shield) token was created by the Era Touch development team. The coin is based on a system of gateways that serve hundreds of servers in different parts of the world. That is, the company uses distributed data registry technology, but its architecture is radically different from a typical blockchain. The task of the coin is to provide a free exchange of assets between users with almost instant transactions and minimal commissions."
ORG_PHYSICAL_ADDRESS="3770 S University Center Dr, Las Vegas, NV 89119"
ORG_PHONE_NUMBER="+1 702-734-6788"
ORG_KEYBASE="Magofox"
ORG_OFFICIAL_EMAIL="eratouch@gmail.com"

[[CURRENCIES]]
code="SWS"
issuer="GAHOVX34KDN2VEXVBTVKKBN57MDZSBCQFFSN7K6AXWVJDL6AZNM3MTZG"
display_decimals= 6
is_asset_anchored=false
name="Sword & Shield"
desc="The coin that included a new type of protection (Sword and Shield) token was created by the Era Touch development team. The coin is based on a system of gateways that serve hundreds of servers in different parts of the world. That is, the company uses distributed data registry technology, but its architecture is radically different from a typical blockchain. The task of the coin is to provide a free exchange of assets between users with almost instant transactions and minimal commissions."
conditions="There will be 1000000000 now and forever"
image="https://i.ibb.co/k5vP9xV/photo-2021-10-10-09-08-57-removebg-preview.png" 
# sword&shield (SWORD&Shield) Token was issued using the open and inclusive Stellar blockchain network.
# Home Domain: eratouch.com
# Sword&Shield Token
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"